### ISSUE TITLE
More gates "doors"

### ISSUE THREAD

**Issue by sutex** [eideehi/valheim-automatics#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

1.4.0

### Is this a bug caused by this mod alone?

The bug was reproduced with this mod alone

### List of mods to reproduce bug

There was a dialog box where you could put the names of MoreGates by RagnarokHCRP mod like "Portcullis" or "Gate" but that has been removed.

### What happened?

Dialog box has been removed

### Steps to reproduce the bug

Walk up to a MoreGates by RagnarokHCRP and none of the gates will open.

**Comment by LordDelacroix** [comment]
Not just that, I'm seeing that some Gates work and other do not.

**Comment by eideehi** [comment]
User custom object definitions have been moved to "User-defined XXXX". Please refer to the link below for details. In my mod, significant changes are made during minor version updates (the "y" part of x.y.z, such as 4 in 1.4.0), so I recommend checking the update history and README.

Also, in version 1.4.0, matching patterns for doors cannot be displayed accurately. This has been fixed in afa5651d071cbdad506966daf0ab7c29be8b8f41, but until the bug fix release, please enter the name of the gate directly in the Pattern field.

[User-defined Door](https://github.com/eideehi/valheim-automatics/blob/1.4.0/CONFIG.adoc#user-defined-door--custom_door)
[Add user-defined object to Automatics](https://github.com/eideehi/valheim-automatics/blob/1.4.0/docs/add-user-defined-object.adoc)
