### ISSUE TITLE
Custom pin icons incompatible with Thunderstore installation

### ISSUE THREAD

**Issue by NumbaOneIsTW** [eideehi/valheim-automatics#4]
Since thunderstore unpacks mods into directories with the format <author>-<mod_name>, custom pin textures aren't applying.

**Comment by eideehi** [comment]
Commit fe1909bc6d5b82bc98ce40e8623cc3fc62814872 closed by mistake. I meant to close #3, not this issue.

**Comment by eideehi** [comment]
This issue is due to the Mod Manager specification, so there seems to be nothing I can do. I will close this issue by adding a note in the README that do not guarantee operation with any Mod Manager other than Vortex.

https://github.com/eideehi/valheim-automatics/blob/e9a1885d50e6542e6a9cc827fdf6c063a3d34257/README.adoc#L66
